### ISSUE TITLE
missing ops

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/HyREPL#11]
- [x] eval
- [x] stdin  
- [x] close

(Should be noted they ain't done, even if they are partially/almost implemented)
- [ ] ls-session
- [X] describe
- [X] interrupt
- [x] load-file

Source:
https://github.com/clojure/tools.nrepl/blob/master/doc/ops.md

**Comment by farhaven** [comment]
cc63ee3e5313182236af927b390bdc1510d19a1f implements `ls-session` as the only remaining op.
