### ISSUE TITLE
Make completion work

### ISSUE THREAD

**Issue by farhaven** [Foxboron/HyREPL#13]
Fireplace runs a big chunk of clojure to generate completion options. Since the chunk of code is not static, we can't use the workarounds mechanism to support that. A solution would be to make workarounds match regular expressions.

**Comment by Foxboron** [comment]
<drunk> OOORRRR we just fork fireplace! </drunk>
:dancer:

**Comment by algernon** [comment]
As far as I saw, cider does something similar too.

**Comment by farhaven** [comment]
Cider uses a custom middleware that provides a `complete` operation. That should be even easier to implement... Maybe we can get the fireplace people to do something similar so we don't have to fork it? That would be an immensive load off our shoulders...

**Comment by farhaven** [comment]
Whoops, I was wrong. The chunk of code fireplace tries to execute is indeed static. It's rather unwieldy though and I'd rather not have that included verbatim in the workarounds module, so the question still stands. We could get away with doing something like hashing the code and see if we have a workaround for that specific hash, but that's hard to maintain.

Suggestions? I'd rather push "forking fireplace" as far into the future as possible because while interesting, that's quite a big additional workload.

**Comment by farhaven** [comment]
So Fox just notified me that the chunk of code is just a fallback and fireplace uses `complete` like cider does. That makes this a lot easier.

**Comment by farhaven** [comment]
Implemented in 8314ad9 and following. Should work in fireplace and cider, I haven't tested anything else yet.
