### ISSUE TITLE
Workarounds suck

### ISSUE THREAD

**Issue by farhaven** [Foxboron/HyREPL#16]
#15 shows it again, our current workaround scheme isn't that great. To support variable forms to be worked around, we should either replace the direct dict lookups with a regex lookup or use a function to decide which (if any) workaround to apply to a piece of code.

**Comment by Foxboron** [comment]
This wasn't meant to be used extensively at all when i first wrote it. Just a quick hack to see if i could get fireplace working.

**Comment by farhaven** [comment]
That is true, but the workarounds system helped us get up and running and I think we can use that in the future, even if we do fork fireplace eventually. I've hacked up a nicer implementation of the current scheme, which is in the `workarounds` branch. Biggest difference is that workarounds are now use to simply modify the code of an expression that's about to be run. It does the trick for macroexpand and friends :)

**Comment by farhaven** [comment]
With 1baaa82d35dde6351e3c5e3eba907de3b32de3db workarounds still suck, but they feel nice while they do.
