### ISSUE TITLE
cider-quit times out

### ISSUE THREAD

**Issue by algernon** [Foxboron/HyREPL#19]
When I do an `M-x cider-quit` in Emacs, HyREPL says on the console:

```
in: {'op': 'close', 'session': '42bf318e-3be5-4b93-a773-6cdbcf6945f8', 'id': '8'}
Client gone
```

Yet, in Emacs, after confirming that I want to quit CIDER, I get a message that the connection was broken by the remote peer, then Emacs hangs for a few seconds until it times out, and I get a message about that too:

```
Are you sure you want to quit CIDER? (y or n) y
nREPL: Connection closed (connection broken by remote peer
)
nrepl-send-sync-request: Sync nREPL request timed out (op close session 42bf318e-3be5-4b93-a773-6cdbcf6945f8 id 8)
```

I suppose the `close` op wants some kind of reply too.

**Comment by farhaven** [comment]
Solved with 74aa4c053d009aedf06231d34b6b96d358b000a9.
