### ISSUE TITLE
Add to PyPI?

### ISSUE THREAD

**Issue by endrebak** [Foxboron/HyREPL#26]
I'm looking to add this to the emacs `hy-mode`.

To simplify installation, I'd love for hyrepl to be available from PyPI and to be able to start it with
```
$ hyreplserver
```

This way you do not have to set the Pythonpath manually, nor install the requirements manually.

I think all you have to do is add a script that starts the hyreplserver file and a `scripts = ["bin/hyreplserver"]` line to setup.py.

Interested?

I can create a PR, but you need to register the project with pypi yourself to update it everytime a new semi-stable version is out.

**Comment by endrebak** [comment]
https://github.com/Foxboron/HyREPL/issues/24

**Comment by Foxboron** [comment]
I'll fix it during the day \o/

**Comment by endrebak** [comment]
If it is installed with pypi you do not need a script btw, just using `hy -m HyREPL.server` is plenty simple.

**Comment by Foxboron** [comment]
I'm considering just throwing up a bin folder with `hyrepl` and those lines added for the simplicity

**Comment by endrebak** [comment]
`-m` and no `.py` can be confusing to newbs, but I guess they aren't the target audience. With a script you can easily add CLI options later though.

**Comment by endrebak** [comment]
Minimal steps needed to upload project (in case you or anyone else don't know how):

Register user and pw at https://pypi.python.org/pypi

Minimal: `.pypirc`

```
[distutils] # this tells distutils what package indexes you can push to
index-servers =
  pypi
  pypitest

[pypi]
repository: https://pypi.python.org/pypi
username: karlpilkington
password: harry_the_housefly
```

Afterwards you just need to 
`python setup.py register; py; python sdist upload # unsafe`

If you have trouble with getting your `setup.py` to work and find no answers online I can create a working version for you. Packaging is easily the worst part of Python.

**Comment by Foxboron** [comment]
I believe i managed to push too pypi now. Please feel free to tell me if you spot any errors
