### ISSUE TITLE
Use different ports?

### ISSUE THREAD

**Issue by endrebak** [Foxboron/HyREPL#28]
If you want to start two servers, one for`middleware.complete` and one to create a REPL for the user you need two ports right?

Would be nice if you could include a port option for the HyREPL script.

**Comment by Foxboron** [comment]
No, you can just connect it to the same server. The middleware only creates new commands. However, allowing a port option is something we indeed lack!
CC: @farhaven

**Comment by Foxboron** [comment]
Added with 9724742c9f30f0
