### ISSUE TITLE
Docrequest: What is `HyREPL.middleware.complete` supposed to be able to complete? 

### ISSUE THREAD

**Issue by endrebak** [Foxboron/HyREPL#33]
```
=> (import pandas)
=> (get-completions "pandas")
['__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
name 'pandas' is not defined
[]
=> (get-completions "pandas.")
*same boom*
```

I'll take it that `HyREPL` isn't meant to be able to complete stuff in modules nor objects?

**Comment by Foxboron** [comment]
It looks like a bug as we do a little bit of magic in the `eval-module` for the sys.stdout overriding. Does it work running it through a HyREPL server contra calling the function?

**Comment by farhaven** [comment]
The `completion` middleware takes the namespace of objects to complete from the `eval` modules evaluation namespace. You can use the `TypedCompleter` class separately though.

**Comment by endrebak** [comment]
Okay then. Perhaps something to document?

And what is the correct way of using the completion engine? Minimal example appreciated. I can flesh out some docs later when I learn more about it.
