### ISSUE TITLE
How are you supposed to use the completion-engine?

### ISSUE THREAD

**Issue by endrebak** [Foxboron/HyREPL#34]
I have gotten completion working in emacs by interacting with an REPL. But that was not the proper way, if I understand correctly.

How are you supposed to interact with the completion engine?

(I tried reading the hy-vim sources to find out, but it seems like it does not support autocomplete.)

One more problem: how are you able to introspect modules/objects? To do that they need to be loaded in the same process as the completion code. Is it up to the plugin developer to solve this problem or is it something HyREPL tries to help with?

**Comment by Foxboron** [comment]
So, HyREPL is a network repl, not a REPL in the traditional sense. Take a look at this project implementing a client for the protocol; https://github.com/cemerick/nrepl-python-client

Completion of modules and/or objects is solved by evaling the lines of code, then the completion middleware should be able to retrieve the objects.

**Comment by farhaven** [comment]
> I tried reading the hy-vim sources to find out, but it seems like it does not support autocomplete.

It does, that's what I wrote HyREPLs completion middleware for :) The nREPL opcode is `complete`, with the partial symbol to look up as its `symbol` arg. Something like this (bencoded of course):

`{"op": "complete", "symbol": "http."}` after importing `http` into the eval middlewares namespace (`HyREPL.middleware.eval.eval-module`) will yield a list of symbols inside the `http` module annotated with their type.

By the way, I've tested HyREPL with emacs' `cider` nREPL client and completion worked there out of the box. Which nREPL client are you using? It sounds like it doesn't support the `describe` operation, which should tell it about `complete`'s availability...

**Comment by endrebak** [comment]
Ah, now I understand more of it. Not using an nrepl client. Tried with Monroe first, but no completion.

I will write a few lines about how to connect to the HyREPL with CIDER. How this works is probably not self-explanatory for people with no Clojure-experience. I was fooled by the fact that Cider has clojure in the name.

Thanks for all your help.

**Comment by Foxboron** [comment]
@endrebak The whole nREPL thing is kinda clojure specific, even tho it's not meant to be. We have reverse engineered a few nREPL clients for clojure and implemented several hacks to get around them.
https://github.com/Foxboron/HyREPL/blob/master/HyREPL/workarounds.hy

Feel free to ask if there are more questions \o/
